//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using NHibernate template.
// Code is generated on: 06.03.2020 15:35:09
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Collections.Generic;

namespace DynamicPDFCreator
{

   
    public partial class AnschreibenTyp {
    
        #region Extensibility Method Definitions
        
        /// <summary>
        /// There are no comments for OnCreated in the schema.
        /// </summary>
        partial void OnCreated();
        
        #endregion
        
        public AnschreibenTyp()
        {
            OnCreated();
        }
        public virtual short id
        {
            get;
            set;
        }
        public virtual string bezeichnung
        {
            get;
            set;
        }
        public virtual bool implementiert
        {
            get;
            set;
        }
        /*
        public virtual ISet<PDF> pdfs
        {
            get;
            set;
        }
        */
    }

}
