//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using NHibernate template.
// Code is generated on: 13.03.2020 11:36:13
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Collections.Generic;

namespace DynamicPDFCreator
{

    /// <summary>
    /// There are no comments for DynamicPDFCreator.TblAnsprechpartnerTyp, DynamicPDFCreator in the schema.
    /// </summary>
    public partial class AnsprechpartnerTyp {
    
        #region Extensibility Method Definitions
        
        /// <summary>
        /// There are no comments for OnCreated in the schema.
        /// </summary>
        partial void OnCreated();
        
        #endregion
        /// <summary>
        /// There are no comments for TblAnsprechpartnerTyp constructor in the schema.
        /// </summary>
        public AnsprechpartnerTyp()
        {
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for IdAnsprechpartnerTyp in the schema.
        /// </summary>
        public virtual short IdAnsprechpartnerTyp
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Typ in the schema.
        /// </summary>
        public virtual string Typ
        {
            get;
            set;
        }

        /*public virtual ISet<PDF> pdfs
        {
            get;
            set;
        }*/
    }

}
