//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using NHibernate template.
// Code is generated on: 06.03.2020 15:35:09
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Collections.Generic;

namespace DynamicPDFCreator
{

    
    public partial class Ansprechpartner {
    
        #region Extensibility Method Definitions
        
        
        partial void OnCreated();
        
        #endregion
        
        public Ansprechpartner()
        {
            OnCreated();
        }

        public virtual int id
        {
            get;
            set;
        }

        public virtual string funktion
        {
            get;
            set;
        }

        public virtual string ansprechpartnerName
        {
            get;
            set;
        }

        public virtual string ansprechpartnerVorname
        {
            get;
            set;
        }

        public virtual string telefon
        {
            get;
            set;
        }

        public virtual string mobil
        {
            get;
            set;
        }

        public virtual string email
        {
            get;
            set;
        }

        public virtual string typ
        {
            get;
            set;
        }

        public virtual string bereich
        {
            get;
            set;
        }

        public virtual string homepage
        {
            get;
            set;
        }

        public virtual string plz
        {
            get;
            set;
        }

        public virtual string ort
        {
            get;
            set;
        }

        public virtual string strasse
        {
            get;
            set;
        }
        public virtual string hausnummer
        {
            get;
            set;
        }

        public virtual string niederlassung
        {
            get;
            set;
        }

        public virtual string nlAbteilung
        {
            get;
            set;
        }

        public virtual string ptiBereich
        {
            get;
            set;
        }

        public virtual string bemerkung
        {
            get;
            set;
        }

        public virtual string firma
        {
            get;
            set;
        }

        //public virtual ISet<Projekt> projekte
        //{
        //    get;
        //    set;
        //}
        //public virtual ISet<PDF> pdfs
        //{
        //    get;
        //    set;
        //}
        /*public virtual ISet<PDF> pdfs
        {
            get;
            set;
        }*/
    }

}
