//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using NHibernate template.
// Code is generated on: 06.03.2020 15:35:09
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Collections.Generic;

namespace DynamicPDFCreator
{

    
    /// There are no comments for DynamicPDFCreator.TblAuftraege, DynamicPDFCreator in the schema.
    
    public partial class Auftragloeschen {
    
        #region Extensibility Method Definitions
        
        
        /// There are no comments for OnCreated in the schema.
        
        partial void OnCreated();
        
        #endregion
        
        /// There are no comments for TblAuftraege constructor in the schema.
        
        public Auftragloeschen()
        {
            this.IdWMSTIStatus = @"ohne WMSTI";
            this.InternWMSTIAbschliessbar = false;
            this.Selektiert = false;
            this.CreateDate = DateTime.Now;
            this.Gemerkt = false;
            this.ZusatzMaterial = 0;
            this.WegesicherungErforderlich = 0;
            this.DatenblattErforderlich = 0;
            this.WegesicherungErledigt = 2;
            this.DatenblattErledigt = 2;
            this.SollDauerPlanung = 0f;
            this.SollDauerDoku = 0;
            this.IdAuftragVeranschlagungshilfe = 0;
            this.IdBaugebiet = 0;
            this.PlanungsLeistungenInHauptauftrag = false;
            this.Markiert = false;
            this.ErstAm = DateTime.Now;
            OnCreated();
        }

    
        
        
        
        public virtual int IdAuftrag
        {
            get;
            set;
        }

    
        
        /// There are no comments for SSMATimeStamp in the schema.
        
        public virtual byte[] SSMATimeStamp
        {
            get;
            set;
        }

    
        
        /// There are no comments for SMNummer in the schema.
        
        public virtual string SMNummer
        {
            get;
            set;
        }

    
        
        /// There are no comments for Requestnummer in the schema.
        
        public virtual string Requestnummer
        {
            get;
            set;
        }

    
        
        /// There are no comments for IdWMSTIStatus in the schema.
        
        public virtual string IdWMSTIStatus
        {
            get;
            set;
        }

    
        
        /// There are no comments for IdBearbeiter in the schema.
        
        public virtual string IdBearbeiter
        {
            get;
            set;
        }

    
        
        /// There are no comments for Bezeichnung in the schema.
        
        public virtual string Bezeichnung
        {
            get;
            set;
        }

    
        
        /// There are no comments for Auftragseingang in the schema.
        
        public virtual System.DateTime Auftragseingang
        {
            get;
            set;
        }

    
        
        /// There are no comments for BAFAKorrigiert in the schema.
        
        public virtual System.DateTime? BAFAKorrigiert
        {
            get;
            set;
        }

    
        
        /// There are no comments for Bemerkung in the schema.
        
        public virtual string Bemerkung
        {
            get;
            set;
        }

    
        
        /// There are no comments for Baubeschreibung in the schema.
        
        public virtual string Baubeschreibung
        {
            get;
            set;
        }

    
        
        /// There are no comments for InternWMSTIAbschliessbar in the schema.
        
        public virtual bool? InternWMSTIAbschliessbar
        {
            get;
            set;
        }

    
        
        /// There are no comments for Selektiert in the schema.
        
        public virtual bool? Selektiert
        {
            get;
            set;
        }

    
        
        /// There are no comments for CreateDate in the schema.
        
        public virtual System.DateTime? CreateDate
        {
            get;
            set;
        }

    
        
        /// There are no comments for UpdateDate in the schema.
        
        public virtual System.DateTime? UpdateDate
        {
            get;
            set;
        }

    
        
        /// There are no comments for IdAuftragnehmerTiefbau in the schema.
        
        public virtual string IdAuftragnehmerTiefbau
        {
            get;
            set;
        }

    
        
        /// There are no comments for IdAuftragnehmerMontage in the schema.
        
        public virtual string IdAuftragnehmerMontage
        {
            get;
            set;
        }

    
        
        /// There are no comments for IdAuftragnehmerPlanung in the schema.
        
        public virtual string IdAuftragnehmerPlanung
        {
            get;
            set;
        }

    
        
        /// There are no comments for IdAuftragnehmerBaubegleitung in the schema.
        
        public virtual string IdAuftragnehmerBaubegleitung
        {
            get;
            set;
        }

    
        
        /// There are no comments for IdAuftragnehmerDokumentation in the schema.
        
        public virtual string IdAuftragnehmerDokumentation
        {
            get;
            set;
        }

    
        
        /// There are no comments for IdAuftraggeber in the schema.
        
        public virtual string IdAuftraggeber
        {
            get;
            set;
        }

    
        
        /// There are no comments for ExportiertAm in the schema.
        
        public virtual System.DateTime? ExportiertAm
        {
            get;
            set;
        }

    
        
        /// There are no comments for Gemerkt in the schema.
        
        public virtual bool? Gemerkt
        {
            get;
            set;
        }

    
        
        /// There are no comments for WMSTIStatusDatum in the schema.
        
        public virtual System.DateTime? WMSTIStatusDatum
        {
            get;
            set;
        }

    
        
        /// There are no comments for PlanungsNummer in the schema.
        
        public virtual string PlanungsNummer
        {
            get;
            set;
        }

    
        
        /// There are no comments for IdProjekt in the schema.
        
        public virtual int? IdProjekt
        {
            get;
            set;
        }

    
        
        /// There are no comments for Postleitzahl in the schema.
        
        public virtual string Postleitzahl
        {
            get;
            set;
        }

    
        
        /// There are no comments for Ort in the schema.
        
        public virtual string Ort
        {
            get;
            set;
        }

    
        
        /// There are no comments for MontAOrtsteil in the schema.
        
        public virtual string MontAOrtsteil
        {
            get;
            set;
        }

    
        
        /// There are no comments for Strasse in the schema.
        
        public virtual string Strasse
        {
            get;
            set;
        }

    
        
        /// There are no comments for Hausnummer in the schema.
        
        public virtual string Hausnummer
        {
            get;
            set;
        }

    
        
        /// There are no comments for MontAZusatzStr in the schema.
        
        public virtual string MontAZusatzStr
        {
            get;
            set;
        }

    
        
        /// wird importiert, kann aber geändert werden
        
        public virtual string Ortsnetz
        {
            get;
            set;
        }

    
        
        /// wird importiert, kann aber geändert werden
        
        public virtual string ASB
        {
            get;
            set;
        }

    
        
        /// muss eingetragen werden - danach kann man mit dem ON + ASB + KVZ  auf die TblKvz zugreifen
        
        public virtual string KVZ
        {
            get;
            set;
        }

    
        
        /// There are no comments for ZusatzMaterial in the schema.
        
        public virtual int? ZusatzMaterial
        {
            get;
            set;
        }

    
        
        /// There are no comments for Langtext in the schema.
        
        public virtual string Langtext
        {
            get;
            set;
        }

    
        
        /// There are no comments for AbrechnungMitidAuftrag in the schema.
        
        public virtual int? AbrechnungMitidAuftrag
        {
            get;
            set;
        }

    
        
        /// There are no comments for WegesicherungErforderlich in the schema.
        
        public virtual int WegesicherungErforderlich
        {
            get;
            set;
        }

    
        
        /// There are no comments for DatenblattErforderlich in the schema.
        
        public virtual int DatenblattErforderlich
        {
            get;
            set;
        }

    
        
        /// There are no comments for WegesicherungErledigt in the schema.
        
        public virtual int WegesicherungErledigt
        {
            get;
            set;
        }

    
        
        /// There are no comments for DatenblattErledigt in the schema.
        
        public virtual int DatenblattErledigt
        {
            get;
            set;
        }

    
        
        /// Zeitpunkt an dem der Auftrag begonnen wird.
        
        public virtual System.DateTime? SollBeginnPlanung
        {
            get;
            set;
        }

    
        
        /// Geschätzte Bearbeitungszeit
        
        public virtual float? SollDauerPlanung
        {
            get;
            set;
        }

    
        
        /// There are no comments for SollEndePlanung in the schema.
        
        public virtual System.DateTime? SollEndePlanung
        {
            get;
            set;
        }

    
        
        /// There are no comments for IstEndePlanung in the schema.
        
        public virtual System.DateTime? IstEndePlanung
        {
            get;
            set;
        }

    
        
        /// There are no comments for MegaplanDatenbank in the schema.
        
        public virtual string MegaplanDatenbank
        {
            get;
            set;
        }

    
        
        /// There are no comments for SollDauerDoku in the schema.
        
        public virtual int? SollDauerDoku
        {
            get;
            set;
        }

    
        
        /// There are no comments for IstEndeDoku in the schema.
        
        public virtual System.DateTime? IstEndeDoku
        {
            get;
            set;
        }

    
        
        /// There are no comments for MegaplanAnsprechpartner in the schema.
        
        public virtual string MegaplanAnsprechpartner
        {
            get;
            set;
        }

    
        
        /// There are no comments for MBfDVertragsnummer in the schema.
        
        public virtual string MBfDVertragsnummer
        {
            get;
            set;
        }

    
        
        /// There are no comments for IdAuftragVeranschlagungshilfe in the schema.
        
        public virtual int? IdAuftragVeranschlagungshilfe
        {
            get;
            set;
        }

    
        
        /// There are no comments for EsassNR in the schema.
        
        public virtual string EsassNR
        {
            get;
            set;
        }

    
        
        /// There are no comments for WegesicherungThema in the schema.
        
        public virtual string WegesicherungThema
        {
            get;
            set;
        }

    
        
        /// There are no comments for WegesicherungErgebnis in the schema.
        
        public virtual string WegesicherungErgebnis
        {
            get;
            set;
        }

    
        
        /// There are no comments for WegesicherungVerschickt in the schema.
        
        public virtual System.DateTime? WegesicherungVerschickt
        {
            get;
            set;
        }

    
        
        /// There are no comments for WegesicherungBestätigt in the schema.
        
        public virtual System.DateTime? WegesicherungBestätigt
        {
            get;
            set;
        }

    
        
        /// There are no comments for WegesicherungUhrzeitvon in the schema.
        
        public virtual System.DateTime? WegesicherungUhrzeitvon
        {
            get;
            set;
        }

    
        
        /// There are no comments for WegesicherungUhrzeitbis in the schema.
        
        public virtual System.DateTime? WegesicherungUhrzeitbis
        {
            get;
            set;
        }

    
        
        /// There are no comments for WegesicherungAnspreichpartner in the schema.
        
        public virtual string WegesicherungAnspreichpartner
        {
            get;
            set;
        }

    
        
        /// There are no comments for WegesicherungTextbox1 in the schema.
        
        public virtual string WegesicherungTextbox1
        {
            get;
            set;
        }

    
        
        /// There are no comments for WegesicherungTextbox2 in the schema.
        
        public virtual string WegesicherungTextbox2
        {
            get;
            set;
        }

    
        
        /// There are no comments for WegesicherungTextbox3 in the schema.
        
        public virtual string WegesicherungTextbox3
        {
            get;
            set;
        }

    
        
        /// There are no comments for WegesicherungAusführungszeitraum in the schema.
        
        public virtual string WegesicherungAusführungszeitraum
        {
            get;
            set;
        }

    
        
        /// There are no comments for WegesicherungBemerkung in the schema.
        
        public virtual string WegesicherungBemerkung
        {
            get;
            set;
        }

    
        
        /// There are no comments for KDName in the schema.
        
        public virtual string KDName
        {
            get;
            set;
        }

    
        
        /// There are no comments for KDVorname in the schema.
        
        public virtual string KDVorname
        {
            get;
            set;
        }

    
        
        /// There are no comments for KDPLZ in the schema.
        
        public virtual string KDPLZ
        {
            get;
            set;
        }

    
        
        /// There are no comments for KDOrt in the schema.
        
        public virtual string KDOrt
        {
            get;
            set;
        }

    
        
        /// There are no comments for KDOrtsteil in the schema.
        
        public virtual string KDOrtsteil
        {
            get;
            set;
        }

    
        
        /// There are no comments for KDStraße in the schema.
        
        public virtual string KDStraße
        {
            get;
            set;
        }

    
        
        /// There are no comments for KDHsNr in the schema.
        
        public virtual string KDHsNr
        {
            get;
            set;
        }

    
        
        /// There are no comments for KDZusatz in the schema.
        
        public virtual string KDZusatz
        {
            get;
            set;
        }

    
        
        /// There are no comments for KDAnsprechpartner in the schema.
        
        public virtual string KDAnsprechpartner
        {
            get;
            set;
        }

    
        
        /// There are no comments for KDTelAnsprechpartner in the schema.
        
        public virtual string KDTelAnsprechpartner
        {
            get;
            set;
        }

    
        
        /// There are no comments for AuftragsfallTI in the schema.
        
        public virtual string AuftragsfallTI
        {
            get;
            set;
        }

    
        
        /// Hier wird f+r dei APL-Aufträge der APL eingetragen
        
        public virtual string APL
        {
            get;
            set;
        }

    
        
        /// Anzahl der Wohneinheiten
        
        public virtual string AnzahlWE
        {
            get;
            set;
        }

    
        
        /// Anzahl der Geschäftseinheiten
        
        public virtual string AnzahlGE
        {
            get;
            set;
        }

    
        
        /// APL innen oder außen
        
        public virtual string Bauweise
        {
            get;
            set;
        }

    
        
        /// There are no comments for IdBaugebiet in the schema.
        
        public virtual int? IdBaugebiet
        {
            get;
            set;
        }

    
        
        /// There are no comments for IdKVZBaugebiet in the schema.
        
        public virtual string IdKVZBaugebiet
        {
            get;
            set;
        }

    
        
        /// There are no comments for BaubeschreibungAPL in the schema.
        
        public virtual string BaubeschreibungAPL
        {
            get;
            set;
        }

    
        
        /// There are no comments for ÜbergeordneteRequestIDAusImport in the schema.
        
        public virtual string ÜbergeordneteRequestIDAusImport
        {
            get;
            set;
        }

    
        
        /// There are no comments for Verzögerungsgrund in the schema.
        
        public virtual string Verzögerungsgrund
        {
            get;
            set;
        }

    
        
        /// There are no comments for CSAuftrag in the schema.
        
        public virtual string CSAuftrag
        {
            get;
            set;
        }

    
        
        /// There are no comments for PlanungsLeistungenInHauptauftrag in the schema.
        
        public virtual bool? PlanungsLeistungenInHauptauftrag
        {
            get;
            set;
        }

    
        
        /// There are no comments for Markiert in the schema.
        
        public virtual bool? Markiert
        {
            get;
            set;
        }

    
        
        /// There are no comments for ErstVon in the schema.
        
        public virtual string ErstVon
        {
            get;
            set;
        }

    
        
        /// There are no comments for ErstAm in the schema.
        
        public virtual System.DateTime? ErstAm
        {
            get;
            set;
        }

    
        
        /// There are no comments for AendVon in the schema.
        
        public virtual string AendVon
        {
            get;
            set;
        }

    
        
        /// There are no comments for AendAm in the schema.
        
        public virtual System.DateTime? AendAm
        {
            get;
            set;
        }

    
        
        /// There are no comments for IDStatusWegesicherung in the schema.
        
        public virtual int? IDStatusWegesicherung
        {
            get;
            set;
        }

    
        
        /// There are no comments for IDStatusBauablauf in the schema.
        
        public virtual int? IDStatusBauablauf
        {
            get;
            set;
        }

    
        
        /// There are no comments for IDStatusQgis in the schema.
        
        public virtual int? IDStatusQgis
        {
            get;
            set;
        }

    
        
        /// There are no comments for IDStatusVeranschlagung in the schema.
        
        public virtual int? IDStatusVeranschlagung
        {
            get;
            set;
        }

    
        
        /// There are no comments for IDStatusBauakte in the schema.
        
        public virtual int? IDStatusBauakte
        {
            get;
            set;
        }

    
        
        /// There are no comments for IDStatusMegaplan in the schema.
        
        public virtual int? IDStatusMegaplan
        {
            get;
            set;
        }

    
        
        /// There are no comments for IDStatusDokumentation in the schema.
        
        public virtual int? IDStatusDokumentation
        {
            get;
            set;
        }

    
        
        /// There are no comments for StatusWegesicherungBemerkung in the schema.
        
        public virtual string StatusWegesicherungBemerkung
        {
            get;
            set;
        }

    
        
        /// There are no comments for StatusBauablaufBemerkung in the schema.
        
        public virtual string StatusBauablaufBemerkung
        {
            get;
            set;
        }

    
        
        /// There are no comments for StatusQgisBemerkung in the schema.
        
        public virtual string StatusQgisBemerkung
        {
            get;
            set;
        }

    
        
        /// There are no comments for StatusVeranschlagungBemerkung in the schema.
        
        public virtual string StatusVeranschlagungBemerkung
        {
            get;
            set;
        }

    
        
        /// There are no comments for StatusBauakteBemerkung in the schema.
        
        public virtual string StatusBauakteBemerkung
        {
            get;
            set;
        }

    
        
        /// There are no comments for StatusMegaplanBemerkung in the schema.
        
        public virtual string StatusMegaplanBemerkung
        {
            get;
            set;
        }

    
        
        /// There are no comments for StatusDokumentationBemerkung in the schema.
        
        public virtual string StatusDokumentationBemerkung
        {
            get;
            set;
        }

    
        
        /// There are no comments for StatusWegesicherungAendVon in the schema.
        
        public virtual string StatusWegesicherungAendVon
        {
            get;
            set;
        }

    
        
        /// There are no comments for StatusWegesicherungZeitpunkt in the schema.
        
        public virtual System.DateTime? StatusWegesicherungZeitpunkt
        {
            get;
            set;
        }

    
        
        /// There are no comments for StatusBauablaufAendVon in the schema.
        
        public virtual string StatusBauablaufAendVon
        {
            get;
            set;
        }

    
        
        /// There are no comments for StatusBauablaufAendAm in the schema.
        
        public virtual System.DateTime? StatusBauablaufAendAm
        {
            get;
            set;
        }

    
        
        /// There are no comments for StatusQgisAendVon in the schema.
        
        public virtual string StatusQgisAendVon
        {
            get;
            set;
        }

    
        
        /// There are no comments for StatusQgisAendAm in the schema.
        
        public virtual System.DateTime? StatusQgisAendAm
        {
            get;
            set;
        }

    
        
        /// There are no comments for StatusVeranschlagungAendVon in the schema.
        
        public virtual string StatusVeranschlagungAendVon
        {
            get;
            set;
        }

    
        
        /// There are no comments for StatusVeranschlagungAendAm in the schema.
        
        public virtual System.DateTime? StatusVeranschlagungAendAm
        {
            get;
            set;
        }

    
        
        /// There are no comments for StatusBauakteAendVon in the schema.
        
        public virtual string StatusBauakteAendVon
        {
            get;
            set;
        }

    
        
        /// There are no comments for StatusBauakteAendAm in the schema.
        
        public virtual System.DateTime? StatusBauakteAendAm
        {
            get;
            set;
        }

    
        
        /// There are no comments for StatusMegaplanAendVon in the schema.
        
        public virtual string StatusMegaplanAendVon
        {
            get;
            set;
        }

    
        
        /// There are no comments for StatusMegaplanAendAm in the schema.
        
        public virtual System.DateTime? StatusMegaplanAendAm
        {
            get;
            set;
        }

    
        
        /// There are no comments for StatusDokumentationAendVon in the schema.
        
        public virtual string StatusDokumentationAendVon
        {
            get;
            set;
        }

    
        
        /// There are no comments for StatusDokumentationAendAm in the schema.
        
        public virtual System.DateTime? StatusDokumentationAendAm
        {
            get;
            set;
        }

    
        
        /// There are no comments for Wunschtermin in the schema.
        
        public virtual System.DateTime? Wunschtermin
        {
            get;
            set;
        }

    
        
        /// There are no comments for Wunschbearbeiter in the schema.
        
        public virtual string Wunschbearbeiter
        {
            get;
            set;
        }

    
        
        /// There are no comments for IDStatusNacharbeiten in the schema.
        
        public virtual int? IDStatusNacharbeiten
        {
            get;
            set;
        }

    
        
        /// There are no comments for StatusNacharbeitenAendAm in the schema.
        
        public virtual System.DateTime? StatusNacharbeitenAendAm
        {
            get;
            set;
        }

    
        
        /// There are no comments for StatusNacharbeitenAendVon in the schema.
        
        public virtual string StatusNacharbeitenAendVon
        {
            get;
            set;
        }

    
        
        /// There are no comments for IDStatusQgisHausanschluesse in the schema.
        
        public virtual int? IDStatusQgisHausanschluesse
        {
            get;
            set;
        }

    
        
        /// There are no comments for StatusQgisHausanschluesseAendAm in the schema.
        
        public virtual System.DateTime? StatusQgisHausanschluesseAendAm
        {
            get;
            set;
        }

    
        
        /// There are no comments for StatusQgisHausanschluesseAendVon in the schema.
        
        public virtual string StatusQgisHausanschluesseAendVon
        {
            get;
            set;
        }

    
        
        /// There are no comments for StatusNacharbeitenBemerkung in the schema.
        
        public virtual string StatusNacharbeitenBemerkung
        {
            get;
            set;
        }

        
    }

}
