//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using NHibernate template.
// Code is generated on: 13.03.2020 11:48:23
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Collections.Generic;

namespace DynamicPDFCreator
{

    /// <summary>
    /// There are no comments for DynamicPDFCreator.TblBearbeiter, DynamicPDFCreator in the schema.
    /// </summary>
    public partial class Bearbeiter {
    
        #region Extensibility Method Definitions
        partial void OnCreated();
        #endregion
        public Bearbeiter()
        {
            OnCreated();
        }
        public virtual string id
        {
            get;
            set;
        }
        public virtual string email
        {
            get;
            set;
        }
        public virtual string telefon
        {
            get;
            set;
        }
        public virtual string bearbeiterName
        {
            get;
            set;
        }
        public virtual string bearbeiterVorname
        {
            get;
            set;
        }
        /*public virtual ISet<PDF> pdfs
        {
            get;
            set;
        }*/
    }

}
