//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using NHibernate template.
// Code is generated on: 06.03.2020 16:57:22
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Collections.Generic;

namespace DynamicPDFCreator
{

    /// <summary>
    /// There are no comments for DynamicPDFCreator.TblAnsprechpartner2Projekt, DynamicPDFCreator in the schema.
    /// </summary>
    public partial class TblAnsprechpartner2Projekt {
    
        #region Extensibility Method Definitions
        
        /// <summary>
        /// There are no comments for OnCreated in the schema.
        /// </summary>
        partial void OnCreated();

        public override bool Equals(object obj)
        {
          TblAnsprechpartner2Projekt toCompare = obj as TblAnsprechpartner2Projekt;
          if (toCompare == null)
          {
            return false;
          }

          if (!Object.Equals(this.IdProjekt, toCompare.IdProjekt))
            return false;
          if (!Object.Equals(this.IdAnsprechpartner, toCompare.IdAnsprechpartner))
            return false;
          
          return true;
        }

        public override int GetHashCode()
        {
          int hashCode = 13;
          hashCode = (hashCode * 7) + IdProjekt.GetHashCode();
          hashCode = (hashCode * 7) + IdAnsprechpartner.GetHashCode();
          return hashCode;
        }
        
        #endregion
        /// <summary>
        /// There are no comments for TblAnsprechpartner2Projekt constructor in the schema.
        /// </summary>
        public TblAnsprechpartner2Projekt()
        {
            this.IdProjekt = 0;
            this.IdAnsprechpartner = 0;
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for IdProjekt in the schema.
        /// </summary>
        public virtual int IdProjekt
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for IdAnsprechpartner in the schema.
        /// </summary>
        public virtual int IdAnsprechpartner
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for SSMATimeStamp in the schema.
        /// </summary>
        public virtual byte[] SSMATimeStamp
        {
            get;
            set;
        }
    }

}
