//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using NHibernate template.
// Code is generated on: 13.03.2020 11:48:23
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Collections.Generic;

namespace DynamicPDFCreator
{

    /// <summary>
    /// There are no comments for DynamicPDFCreator.TblWesiTeam, DynamicPDFCreator in the schema.
    /// </summary>
    public partial class TblWesiTeam {
    
        #region Extensibility Method Definitions
        
        /// <summary>
        /// There are no comments for OnCreated in the schema.
        /// </summary>
        partial void OnCreated();
        
        #endregion
        /// <summary>
        /// There are no comments for TblWesiTeam constructor in the schema.
        /// </summary>
        public TblWesiTeam()
        {
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for Id in the schema.
        /// </summary>
        public virtual short Id
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Firma in the schema.
        /// </summary>
        public virtual string Firma
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Stadt in the schema.
        /// </summary>
        public virtual string Stadt
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for PLZ in the schema.
        /// </summary>
        public virtual string PLZ
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Strasse in the schema.
        /// </summary>
        public virtual string Strasse
        {
            get;
            set;
        }
    
        /// <summary>
        /// There are no comments for Bereich in the schema.
        /// </summary>
        public virtual string Bereich
        {
            get;
            set;
        }
        public virtual string Email
        {
            get;
            set;
        }
        public virtual string Niederlassung
        {
            get;
            set;
        }
    }

}
