//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using NHibernate template.
// Code is generated on: 06.03.2020 15:35:09
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Collections.Generic;

namespace DynamicPDFCreator
{

    /// <summary>
    /// There are no comments for DynamicPDFCreator.TblAnsprechpartner, DynamicPDFCreator in the schema.
    /// </summary>
    public partial class TblAnsprechpartner {
    
        #region Extensibility Method Definitions
        
        /// <summary>
        /// There are no comments for OnCreated in the schema.
        /// </summary>
        partial void OnCreated();
        
        #endregion
        /// <summary>
        /// There are no comments for TblAnsprechpartner constructor in the schema.
        /// </summary>
        public TblAnsprechpartner()
        {
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for IdAnsprechpartner in the schema.
        /// </summary>
        public virtual int IdAnsprechpartner
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for SSMATimeStamp in the schema.
        /// </summary>
        public virtual byte[] SSMATimeStamp
        {
            get;
            set;
        }

    
        /// <summary>
        /// wird aus tblAnsprechpartnerFunktion ausgewählt
        /// </summary>
        public virtual string Funktion
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for AnsprechpartnerName in the schema.
        /// </summary>
        public virtual string AnsprechpartnerName
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for AnsprechpartnerVorname in the schema.
        /// </summary>
        public virtual string AnsprechpartnerVorname
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Telefon in the schema.
        /// </summary>
        public virtual string Telefon
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Mobil in the schema.
        /// </summary>
        public virtual string Mobil
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Email in the schema.
        /// </summary>
        public virtual string Email
        {
            get;
            set;
        }

    
        /// <summary>
        /// wird aus tblAnsprechpartnerFunktion ausgewählt
        /// </summary>
        public virtual string Typ
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Bereich in the schema.
        /// </summary>
        public virtual string Bereich
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Homepage in the schema.
        /// </summary>
        public virtual string Homepage
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for PLZ in the schema.
        /// </summary>
        public virtual string PLZ
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Ort in the schema.
        /// </summary>
        public virtual string Ort
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Straße in the schema.
        /// </summary>
        public virtual string Straße
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Niederlassung in the schema.
        /// </summary>
        public virtual string Niederlassung
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for NLAbteilung in the schema.
        /// </summary>
        public virtual string NLAbteilung
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for PTIBereich in the schema.
        /// </summary>
        public virtual string PTIBereich
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Bemerkung in the schema.
        /// </summary>
        public virtual string Bemerkung
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Firma in the schema.
        /// </summary>
        public virtual string Firma
        {
            get;
            set;
        }
    }

}
