//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using NHibernate template.
// Code is generated on: 06.03.2020 16:57:22
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Collections.Generic;

namespace DynamicPDFCreator
{

    /// <summary>
    /// There are no comments for DynamicPDFCreator.TblProjekte, DynamicPDFCreator in the schema.
    /// </summary>
    public partial class Projekt {
    
        #region Extensibility Method Definitions
        
        /// <summary>
        /// There are no comments for OnCreated in the schema.
        /// </summary>
        partial void OnCreated();
        
        #endregion
        /// <summary>
        /// There are no comments for TblProjekte constructor in the schema.
        /// </summary>
        public Projekt()
        {
            this.FaktorKNB0 = 0f;
            this.FaktorKNB1 = 0f;
            this.AnzahlAdTransMax = 0;
            this.AnzahlMFG15Max = 0;
            this.AnzahlMFG15MaxWT = 0;
            this.IdAuftrag = 0;
            this.Inaktiv = false;
            this.AnzahlMiniMsanMax = 0;
            this.AnzahlMFG12Max = 0;
            this.AnzahlMFG12MaxWT = 0;
            this.Markiert = false;
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for IdProjekt in the schema.
        /// </summary>
        public virtual int IdProjekt
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for SSMATimeStamp in the schema.
        /// </summary>
        public virtual byte[] SSMATimeStamp
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Projekt in the schema.
        /// </summary>
        public virtual string Projekt
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for BemerkungProjekt in the schema.
        /// </summary>
        public virtual string BemerkungProjekt
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for FaktorKNB0 in the schema.
        /// </summary>
        public virtual float? FaktorKNB0
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for FaktorKNB1 in the schema.
        /// </summary>
        public virtual float? FaktorKNB1
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for AnzahlAdTransMax in the schema.
        /// </summary>
        public virtual int? AnzahlAdTransMax
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for AnzahlMFG15Max in the schema.
        /// </summary>
        public virtual int? AnzahlMFG15Max
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for AnzahlMFG15MaxWT in the schema.
        /// </summary>
        public virtual int? AnzahlMFG15MaxWT
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for HerstellerMFG15 in the schema.
        /// </summary>
        public virtual string HerstellerMFG15
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for HerstellerMFG18 in the schema.
        /// </summary>
        public virtual string HerstellerMFG18
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for HerstellerStromsäule in the schema.
        /// </summary>
        public virtual string HerstellerStromsäule
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for IdBearbeiter in the schema.
        /// </summary>
        public virtual string IdBearbeiter
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for IdAuftrag in the schema.
        /// </summary>
        public virtual int? IdAuftrag
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Inaktiv in the schema.
        /// </summary>
        public virtual bool? Inaktiv
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for AnzahlMiniMsanMax in the schema.
        /// </summary>
        public virtual int? AnzahlMiniMsanMax
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for AnzahlMFG12Max in the schema.
        /// </summary>
        public virtual int? AnzahlMFG12Max
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for AnzahlMFG12MaxWT in the schema.
        /// </summary>
        public virtual int? AnzahlMFG12MaxWT
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for StreetviewPfad in the schema.
        /// </summary>
        public virtual string StreetviewPfad
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Linkbaustein1 in the schema.
        /// </summary>
        public virtual string Linkbaustein1
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Linkbaustein2 in the schema.
        /// </summary>
        public virtual string Linkbaustein2
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Linkbaustein3 in the schema.
        /// </summary>
        public virtual string Linkbaustein3
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Fertigstellung in the schema.
        /// </summary>
        public virtual System.DateTime? Fertigstellung
        {
            get;
            set;
        }

    
        /// <summary>
        /// Art des Projektes 0= Sonstiges 1= APL-Projket
        /// </summary>
        public virtual string Projekttyp
        {
            get;
            set;
        }

    
        /// <summary>
        /// Kennzeichnung ob Glas oder Kupfer
        /// </summary>
        public virtual string Medium
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for IdProjekttyp in the schema.
        /// </summary>
        public virtual string IdProjekttyp
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for IDNLPTI in the schema.
        /// </summary>
        public virtual string IDNLPTI
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for BemerkungProjektÜbersicht in the schema.
        /// </summary>
        public virtual string BemerkungProjektÜbersicht
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for IDProjektWegesicherung in the schema.
        /// </summary>
        public virtual string IDProjektWegesicherung
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Markiert in the schema.
        /// </summary>
        public virtual bool? Markiert
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for IdAuftragnehmerTiefbau in the schema.
        /// </summary>
        public virtual string IdAuftragnehmerTiefbau
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for IdAuftragnehmerMontage in the schema.
        /// </summary>
        public virtual string IdAuftragnehmerMontage
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for IdAuftragnehmerPlanung in the schema.
        /// </summary>
        public virtual string IdAuftragnehmerPlanung
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for IdAuftragnehmerBaubegleitung in the schema.
        /// </summary>
        public virtual string IdAuftragnehmerBaubegleitung
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for IdAuftragnehmerDokumentation in the schema.
        /// </summary>
        public virtual string IdAuftragnehmerDokumentation
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for IdAuftraggeber in the schema.
        /// </summary>
        public virtual string IdAuftraggeber
        {
            get;
            set;
        }

        public virtual List<Ansprechpartner> Ansprechpartner
        {
            get;
            set;
        }
    }

}
