//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynamicPDFCreator.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorCodes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorCodes() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DynamicPDFCreator.Properties.ErrorCodes", typeof(ErrorCodes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Es gab ein Problem mit dem Absender. Bitte erneut probieren oder aaron.boden@eictronic.de bzw. 036071369018 kontaktiern ähnelt.
        /// </summary>
        internal static string ERROR_ABSENDER {
            get {
                return ResourceManager.GetString("ERROR_ABSENDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Es gab ein Problem mit dem Typ des Anschreibens. Bitte erneut probieren oder aaron.boden@eictronic.de bzw. 036071369018 kontaktiern ähnelt.
        /// </summary>
        internal static string ERROR_ANSCHREIBENTYP {
            get {
                return ResourceManager.GetString("ERROR_ANSCHREIBENTYP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Es gab ein Problem mit dem Ansprechpartner. Bitte erneut probieren oder aaron.boden@eictronic.de bzw. 036071369018 kontaktiern ähnelt.
        /// </summary>
        internal static string ERROR_ANSPRECHPARTNER {
            get {
                return ResourceManager.GetString("ERROR_ANSPRECHPARTNER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Es gab ein Problem mit dem AnsprechpartnerBau. Bitte erneut probieren oder aaron.boden@eictronic.de bzw. 036071369018 kontaktiern ähnelt.
        /// </summary>
        internal static string ERROR_ANSPRECHPARTNER_BAU {
            get {
                return ResourceManager.GetString("ERROR_ANSPRECHPARTNER_BAU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Es gab ein Problem mit dem Ausführungszeitraum. Bitte erneut probieren oder aaron.boden@eictronic.de bzw. 036071369018 kontaktiern ähnelt.
        /// </summary>
        internal static string ERROR_AUSFUEHRUNGSZEITRAUM {
            get {
                return ResourceManager.GetString("ERROR_AUSFUEHRUNGSZEITRAUM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Anscheinend befinden sich unerlaubte Zeichen im Textfeld &quot;Beschreibung mit wem das Vorhaben abgesprochen wurde&quot; ähnelt.
        /// </summary>
        internal static string ERROR_BESCHREIBUNG_ABGESPROCHEN_MIT {
            get {
                return ResourceManager.GetString("ERROR_BESCHREIBUNG_ABGESPROCHEN_MIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Anscheinend befinden sich unerlaubte Zeichen im Textfeld &quot;Beischreibung der Maßnahme&quot; ähnelt.
        /// </summary>
        internal static string ERROR_BESCHREIBUNGMASSNAHME {
            get {
                return ResourceManager.GetString("ERROR_BESCHREIBUNGMASSNAHME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Es gab ein Problem mit den Checkboxen. Bitte erneut probieren oder aaron.boden@eictronic.de bzw. 036071369018 kontaktiern ähnelt.
        /// </summary>
        internal static string ERROR_CHECKBOXEN {
            get {
                return ResourceManager.GetString("ERROR_CHECKBOXEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Es gab ein Problem mit dem Datum. Bitte erneut probieren oder aaron.boden@eictronic.de bzw. 036071369018 kontaktiern ähnelt.
        /// </summary>
        internal static string ERROR_DATUM {
            get {
                return ResourceManager.GetString("ERROR_DATUM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Es gab ein Problem mit dem Empfänger. Bitte erneut probieren oder aaron.boden@eictronic.de bzw. 036071369018 kontaktiern ähnelt.
        /// </summary>
        internal static string ERROR_EMPFAENGER {
            get {
                return ResourceManager.GetString("ERROR_EMPFAENGER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Anscheinend befinden sich unerlaubte Zeichen im Textfeld &quot;Ort der Maßnahme&quot; ähnelt.
        /// </summary>
        internal static string ERROR_ORTDERMASSNAHME {
            get {
                return ResourceManager.GetString("ERROR_ORTDERMASSNAHME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die SMNummer nicht gefunden ähnelt.
        /// </summary>
        internal static string ERROR_SMNUMMER {
            get {
                return ResourceManager.GetString("ERROR_SMNUMMER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Es gab ein Problem mit der Wesi Teamadresse. Bitte erneut probieren oder aaron.boden@eictronic.de bzw. 036071369018 kontaktiern ähnelt.
        /// </summary>
        internal static string ERROR_WESI_TEAM_ADRESSE {
            get {
                return ResourceManager.GetString("ERROR_WESI_TEAM_ADRESSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Es gab ein Problem mit den Zusatzfeldern. Bitte erneut probieren oder aaron.boden@eictronic.de bzw. 036071369018 kontaktiern ähnelt.
        /// </summary>
        internal static string ERROR_ZUSATZ {
            get {
                return ResourceManager.GetString("ERROR_ZUSATZ", resourceCulture);
            }
        }
    }
}
